POST http://localhost:9000/livros/
Content-Type: application/json

{
    "titulo": "entendendo algoritmos",
    "preco" : 777,
    "paginas" : 200,
    "editora" : "dev lucas",
    "sold": false
}

###

GET http://localhost:9000/livros