
POST http://localhost:9000/livros/
Content-Type: application/json

{
    "titulo": "Nosso Livro de Historias",
    "preco" : 777,
    "paginas" : 777,
    "editora" : "Lucas",
    "sold": false,
    "autor" : "65d631772bd665ec3a78526f"
}

###

GET http://localhost:9000/livros/busca?sold=false

###

PUT http://localhost:9000/livros/65ce24e218a9b4feee33ebf9
Content-Type:  application/json

{
    "titulo": "Senhor dos aneis"
    //"editora": "teste",
    //"preco": 77,
    //"paginas": 777,
    //"sold": false
}

###

DELETE http://localhost:9000/livros/65d636ea00fcfd222f437cd2

###

POST http://localhost:9000/autores/
Content-Type: application/json

{
    "nome" : "Lucas Santana and Jasna Santos",
    "nacionalidade" : "Brazil"
}

###

GET http://localhost:9000/autores/

###

PUT http://localhost:9000/autores/
Content-Type: application/json

{

}

###

DELETE http://localhost:9000/autores/65d6372d5c1c2680ee5351a6